name:          AG2Nurun Code Guide
description:   Diretrizes para os desenvolvedores frontend
url:           http://mdanemberg.github.io/code-guide

markdown:      rdiscount
permalink:     pretty
pygments:      true
